datasource:
  type: mysql
  host: 192.168.1.122 
  port: 3307
  username: root
  password: root
  database: ry_vue
  autoLoadEntities: true
  synchronize: false
  charset: utf8mb4
  timezone: '+08:00'
  # 连接池配置
  pool:
    connectionLimit: 20      # 最大连接数
    waitForConnections: true
    queueLimit: 0
    connectTimeout: 30000